version: '3.8'

services:
  vote:
    image: axelgiovannai/vote:latest
    ports:
      - "${VOTE_PORT}:8080"
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  result:
    image: axelgiovannai/result:latest
    ports:
      - "${RESULT_PORT}:8888"
    networks:
      - frontend
      - backend
    secrets:
      - db_password   
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  worker:
    image: axelgiovannai/worker:latest
    networks:
      - backend
    secrets:
      - db_password   
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    networks:
      - backend
    volumes:
      - redis-data:/data

  db:
    image: postgres:15-alpine
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db_password   
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password  
    deploy:
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend

volumes:
  db-data:
  redis-data:

networks:
  frontend:
  backend:

secrets:
  db_password:
    external: true